### ISSUE TITLE
can't show figures using data_types.ipynb

### ISSUE THREAD

**Issue by xuzhang5788** [blondegeek/e3nn_tutorial#6]
Thank you for your tutorial.  fig.show() didn't show any figures at cell [1],[6],[7]. I don't know why.

In addition, if using sphten = SphericalTensor(tensor, lmax=L), I got error messages. I checked class Spherical Tensor() and changed it into sphten = SphericalTensor(tensor). It works. I am not sure if it is a bug

**Comment by blondegeek** [comment]
Thanks for the message. I need to update the tutorials because the
arguments for SphericalTensor changes recently. You’re absolutely right
that all you need to change is leave off the lmax arg. Also, the keyword n
is now res for the SphericalTensor.plot method.

**Comment by blondegeek** [comment]
Resolved with https://github.com/blondegeek/e3nn_tutorial/commit/e4c560628c1831e04316b1663f4b3592fe7c2582

**Comment by xuzhang5788** [comment]
@blondegeek 
Thank you for your update. I figured out the reason that my figures were not showed at Jupyter notebook is my firefox can not support WebGL. But my chrome is okay. Just for information.

**Comment by blondegeek** [comment]
Good to know!
