### ISSUE TITLE
Referencing se3cnn in data_types.ipynb

### ISSUE THREAD

**Issue by claireannewest** [blondegeek/e3nn_tutorial#7]
Throughout the file [data_types.ipynb](https://github.com/blondegeek/e3nn_tutorial/blob/0.0/data_types.ipynb), se3cnn is being referenced instead of e3nn.

**Comment by blondegeek** [comment]
Resolved in https://github.com/blondegeek/e3nn_tutorial/commit/431fa15fc0d26702ac3343317604c15534a9f81a
