### ISSUE TITLE
Tutorial questions

### ISSUE THREAD

**Issue by bdice** [blondegeek/e3nn_tutorial#8]
Hi! I read through the rendered HTML version of the notebooks (very helpful), but I had some difficulty executing the notebooks due to an unexpected keyword argument and some e3nn API updates. I'll make a PR to fix the API updates, but I'm not sure what to do about the unexpected keyword argument. Any insight would be appreciated. Thanks in advance!

In this cell of the notebook `simple_tasks_and_symmetry.ipynb`:
```python
model = Network()

optimizer = torch.optim.Adam(model.parameters(), 1e-2)
```

I got this error:
```pytb
<ipython-input-5-32a57fc24d23>:1: DeprecationWarning: Call to deprecated function GatedConvParityNetwork.
  model = Network()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-32a57fc24d23> in <module>
----> 1 model = Network()
      2 
      3 optimizer = torch.optim.Adam(model.parameters(), 1e-2)

~/.../lib/python3.8/site-packages/e3nn-0.1.0-py3.8-linux-x86_64.egg/e3nn/util/deprecation.py in new_func(*args, **kwargs)
     17                       stacklevel=2)
     18         warnings.simplefilter('default', DeprecationWarning)  # reset filter
---> 19         return func(*args, **kwargs)
     20     return new_func

TypeError: __init__() got an unexpected keyword argument 'feature_product'
```

### Software versions
```
pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch
torch-cluster             1.5.8                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.8                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchaudio                0.7.0                      py38    pytorch
torchvision               0.8.1                py38_cu110    pytorch
```

e3nn_tutorial commit 431fa15fc0d26702ac3343317604c15534a9f81a
e3nn commit 4c12f848c07e5d1b149ff9a68f525c7e2e6f885b

**Comment by blondegeek** [comment]
Ah! feature_product was removed as an option a while ago. I need to update the tutorial to reflect this. If you have time, feel free to make a pull request of the notebook with this modification (make sure to "Clear all outputs" so you don't commit any huge plotly files). Thanks for pointing this out!

**Comment by blondegeek** [comment]
Oops! Just saw your pull request. Thanks!
